spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: 1234
  security:
    oauth2:
      client:
        registration:
          keycloak:
            scope: openid, profile
            client-id: <<client-id>>
            client-secret: <<client-secret>>
        provider:
          keycloak:
            issuer-uri: https://login.martijnklene.nl/auth/realms/blog
logging:
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
