on:
  release:
    types: [published]

name: Build
jobs:
  Build:
    name: Build Jar file
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Upload jar for job 1
        uses: actions/upload-artifact@v1
        with:
          name: jarpack
          path: ./target


  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    needs: [Build]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Download jar for job 2
        uses: actions/download-artifact@v1
        with:
          name: jarpack
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v1
        with:
          path: .
          dockerfile: ./Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mtijnnl/admin
          tags: ${{steps.tag.outputs.tag}}
